// <auto-generated />
using System;
using BookingManagementService.Appdbcontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookingManagementService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220603103700_bookingtable3")]
    partial class bookingtable3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookingManagementService.Models.TicketDetailTbl", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<int>("FlightNumber");

                    b.Property<string>("PNR");

                    b.Property<DateTime>("endingTime");

                    b.Property<int>("passengerAge");

                    b.Property<int>("passengerGender");

                    b.Property<string>("passengerName");

                    b.Property<DateTime>("startingTime");

                    b.HasKey("userid");

                    b.ToTable("TicketDetailTbl");
                });
#pragma warning restore 612, 618
        }
    }
}
