// <auto-generated />
using System;
using AirLineAPIService.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AirLineAPIService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220529013453_airlineservice")]
    partial class airlineservice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AirLineAPIService.Models.Airline", b =>
                {
                    b.Property<int>("AirlineNo");

                    b.Property<bool>("IsBlocked");

                    b.Property<string>("airlineLogo");

                    b.Property<string>("contactAddress");

                    b.Property<int>("contactNumber");

                    b.HasKey("AirlineNo");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("AirLineAPIService.Models.Inventory", b =>
                {
                    b.Property<int>("FlightNumber");

                    b.Property<int>("BusinessSeats");

                    b.Property<DateTime>("EndDatetime");

                    b.Property<int>("FK_AirlineNo");

                    b.Property<string>("Fromplace");

                    b.Property<int>("NonBusinessSeats");

                    b.Property<int>("NumberOfRows");

                    b.Property<string>("Toplace");

                    b.Property<int>("instrumentUsed");

                    b.Property<int>("meal");

                    b.Property<DateTime>("startDatetime");

                    b.Property<int>("ticketCost");

                    b.HasKey("FlightNumber");

                    b.HasIndex("FK_AirlineNo");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("AirLineAPIService.Models.Inventory", b =>
                {
                    b.HasOne("AirLineAPIService.Models.Airline", "Airlines")
                        .WithMany("Inventories")
                        .HasForeignKey("FK_AirlineNo")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
